# Generated by Django 4.2.7 on 2025-06-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Planta',
                'verbose_name_plural': 'Tipos de Planta',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre común')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Nombre científico')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_images/', verbose_name='Imagen')),
                ('audio', models.FileField(blank=True, null=True, upload_to='species_audio/', verbose_name='Audio')),
                ('kingdom', models.CharField(blank=True, max_length=100, verbose_name='Reino')),
                ('phylum', models.CharField(blank=True, max_length=100, verbose_name='Filo')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Clase')),
                ('order', models.CharField(blank=True, max_length=100, verbose_name='Orden')),
                ('family', models.CharField(blank=True, max_length=100, verbose_name='Familia')),
                ('genus', models.CharField(blank=True, max_length=100, verbose_name='Género')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Tamaño')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Peso')),
                ('lifespan', models.CharField(blank=True, max_length=100, verbose_name='Esperanza de vida')),
                ('habitat', models.TextField(blank=True, verbose_name='Hábitat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('conservation_status', models.CharField(choices=[('NE', 'No Evaluada'), ('DD', 'Datos Insuficientes'), ('LC', 'Preocupación Menor'), ('NT', 'Casi Amenazada'), ('VU', 'Vulnerable'), ('EN', 'En Peligro'), ('CR', 'En Peligro Crítico'), ('EW', 'Extinta en Estado Silvestre'), ('EX', 'Extinta')], default='NE', max_length=2, verbose_name='Estado de conservación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='common.category', verbose_name='Categoría')),
                ('locations', models.ManyToManyField(blank=True, related_name='%(class)s_locations', to='common.location', verbose_name='Ubicaciones')),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='plants.planttype', verbose_name='Tipo de planta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['name'],
            },
        ),
    ]
